name: mutation

on:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * *"

jobs:
  mutation:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: node test/mutate.mjs
